import Provider from "@/components/provider";
import "./globals.css";
import { AuthOptions } from "next-auth";
import { Nav } from "@/components/Nav.js";
import { Open_Sans } from "next/font/google";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const open_Sans = Open_Sans({ subsets: ["latin"], weight: "400" });
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export default async function RootLayout({ children ,mainblogs,sideblogs}) {
  return (
    <html lang="en" className={open_Sans.className}>
      <body>
        <Provider>
          <Nav />
          {children}
          {mainblogs}
          {sideblogs}
        </Provider>
      </body>
    </html>
  );
}
