import Provider from "@/components/provider";
import "./globals.css";
import { AuthOptions } from "next-auth";
import { Nav } from "@/components/Nav.js";

import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export default async function  RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <Provider >
          {/* <Topbar/> */}
          <Nav  />
          {children}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
