import Provider from "@/components/provider";
import "./globals.css";
import { AuthOptions } from "next-auth";
import { Nav } from "@/components/Nav.js";

import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export default async function  RootLayout({ children }) {
  const session=await getServerSession(authOptions)
  console.log("layout session",session?.user.name)
  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          {/* <Topbar/> */}
          <Nav session={session} />
          {children}
          <Footer session={session}/>
        </Provider>
      </body>
    </html>
  );
}
